name: addons-release

on:
  release:
    types: [published]
    tags:
      - v*
  push:
    branches:
      - master-test
      - r*
  pull_request:
    branches:
      - master-test
      - r*

env:
  MIN_PY_VERSION: '3.7'
  MAX_PY_VERSION: '3.10'

jobs:
  release-wheel:
    name: Test and build release wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # To switch on windows-2022/latest, please verify the bazel version:
        # https://github.com/bazelbuild/bazel/issues/14232#issuecomment-1011247429
        os: ['macos-11']
        py-version: ['3.10']
        tf-version: ['2.9.1']
        cpu: ['arm64']
        exclude:
          - py-version: '3.10'
            tf-version: '2.7.3'
      fail-fast: false
    steps:
      - uses: actions/github-script@0.3.0
        id: author-date
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const commit_details = await github.git.getCommit({owner: context.repo.owner, repo: context.repo.repo, commit_sha: context.sha});
            return commit_details.data.author.date
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py-version }}
      - if: matrix.os != 'ubuntu-18.04'
        name: Setup Bazel
        # Ubuntu bazel is run inside of the docker image
        run: bash tools/install_deps/install_bazelisk.sh ./
      - name: Build wheels
        env:
          OS: ${{ runner.os }}
          PY_VERSION: ${{ matrix.py-version }}
          TF_VERSION: ${{ matrix.tf-version }}
          NIGHTLY_TIME: ${{ steps.author-date.outputs.result }}
          CPU: ${{ matrix.cpu }}
        shell: bash
        run: bash .github/workflows/make_wheel_${OS}_${CPU}.sh
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ runner.os }}-${{ matrix.py-version }}-tf${{ matrix.tf-version }}-${{ matrix.cpu }}-wheel
          path: wheelhouse
